from ispyb_client.paths.ispyb_api_v1_legacy_proposal_proposal_id_data_collections_group_data_collections_group_id_stats.get import ApiForget


class IspybApiV1LegacyProposalProposalIdDataCollectionsGroupDataCollectionsGroupIdStats(
    ApiForget,
):
    pass
