
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-25T18:18:12+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "13a160bb78e948ffc5eb81261cd5802977a3db17",
 "version": "2.10.9.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
