# coding: utf-8

"""
    Internal API

    SmartDiagnostics REST API for internal users only  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import smart_diagnostics_client
from smart_diagnostics_client.models.service_resource_child import ServiceResourceChild  # noqa: E501
from smart_diagnostics_client.rest import ApiException


class TestServiceResourceChild(unittest.TestCase):
    """ServiceResourceChild unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceResourceChild(self):
        """Test ServiceResourceChild"""
        # FIXME: construct object with mandatory attributes with example values
        # model = smart_diagnostics_client.models.service_resource_child.ServiceResourceChild()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
