MINUTES_PER_HOUR = 60
HORS_PER_DAY = 24
SECONDS_PER_MINUTE = 60

SECONDS_PER_HOUR = SECONDS_PER_MINUTE * MINUTES_PER_HOUR
SECONDS_PER_DAY = SECONDS_PER_HOUR * HORS_PER_DAY

DEETLIST_URLS = {
    "MAZE_ISLAND": "",
    "HEROIC_RACE": "",
    "ALL_DRAGONS": "",
}