#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2204-99-ge09a38d8"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2204
#define NETGEN_VERSION_TWEAK 99
#define NETGEN_VERSION_HASH "ge09a38d8"
#endif // NETGEN_VERSION_HPP_INCLUDED
