# coding: utf-8

"""
    py-ISPyB

    FastAPI Prototype  # noqa: E501

    The version of the OpenAPI document: 0.1alpha
    Generated by: https://openapi-generator.tech
"""

from ispyb_client.paths.ispyb_api_v1_auth_config.get import ConfigIspybApiV1AuthConfigGet
from ispyb_client.paths.ispyb_api_v1_auth_login.post import LoginIspybApiV1AuthLoginPost


class AuthenticationApi(
    ConfigIspybApiV1AuthConfigGet,
    LoginIspybApiV1AuthLoginPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
