# coding: utf-8

"""
    Internal API

    SmartDiagnostics REST API for internal users only  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import smart_diagnostics_client
from smart_diagnostics_client.models.asset_classification_parameter_value_child import AssetClassificationParameterValueChild  # noqa: E501
from smart_diagnostics_client.rest import ApiException


class TestAssetClassificationParameterValueChild(unittest.TestCase):
    """AssetClassificationParameterValueChild unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssetClassificationParameterValueChild(self):
        """Test AssetClassificationParameterValueChild"""
        # FIXME: construct object with mandatory attributes with example values
        # model = smart_diagnostics_client.models.asset_classification_parameter_value_child.AssetClassificationParameterValueChild()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
