
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-29T15:31:48+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "1fc18fb8076a5a71549e741a322b8b3f68a7a440",
 "version": "2.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
