# coding: utf-8

"""
    py-ISPyB

    FastAPI Prototype  # noqa: E501

    The version of the OpenAPI document: 0.1alpha
    Generated by: https://openapi-generator.tech
"""

from ispyb_client.paths.ispyb_api_v1_options.get import GetOptions
from ispyb_client.paths.ispyb_api_v1_options_ui.get import GetUiOptions
from ispyb_client.paths.ispyb_api_v1_options.patch import UpdateOptions


class OptionsApi(
    GetOptions,
    GetUiOptions,
    UpdateOptions,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
