
# This file was generated by 'versioneer.py' (0.27) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-20T23:26:23-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "fa63337702fef729bd0804f496edde17e3918251",
 "version": "0.5.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
