# coding: utf-8

"""
    nativeSDK

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import native_sdk_core
from native_sdk_core.models.http_validation_error import HTTPValidationError  # noqa: E501
from native_sdk_core.rest import ApiException


class TestHTTPValidationError(unittest.TestCase):
    """HTTPValidationError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHTTPValidationError(self):
        """Test HTTPValidationError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = native_sdk_core.models.http_validation_error.HTTPValidationError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
