VERSION_YEAR = 2022
VERSION_MONTH = int('11')
VERSION_DAY = int('28')
VERSION_HOUR = int('04')
VERSION_MINUTE = int('44')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202211280444
version_date = '2022/11/28 04:44'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
