# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle_sdk
from circle_sdk.model.cancel_payment_response import CancelPaymentResponse
from circle_sdk import configuration


class TestCancelPaymentResponse(unittest.TestCase):
    """CancelPaymentResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
