# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle_sdk
from circle_sdk.model.business_payout import BusinessPayout
from circle_sdk import configuration


class TestBusinessPayout(unittest.TestCase):
    """BusinessPayout unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
