# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle_sdk
from circle_sdk.model.fiat_payment import FiatPayment
from circle_sdk import configuration


class TestFiatPayment(unittest.TestCase):
    """FiatPayment unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
