# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle_sdk
from circle_sdk.model.external_fiat_account_status import ExternalFiatAccountStatus
from circle_sdk import configuration


class TestExternalFiatAccountStatus(unittest.TestCase):
    """ExternalFiatAccountStatus unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
