# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle_sdk
from circle_sdk.model.payment_intent_amount_paid import PaymentIntentAmountPaid
from circle_sdk import configuration


class TestPaymentIntentAmountPaid(unittest.TestCase):
    """PaymentIntentAmountPaid unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
