# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle_sdk
from circle_sdk.model.transfer_detailed_transfer import TransferDetailedTransfer
from circle_sdk import configuration


class TestTransferDetailedTransfer(unittest.TestCase):
    """TransferDetailedTransfer unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
