# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle_sdk
from circle_sdk.model.mock_ach_account_creation_request import MockAchAccountCreationRequest
from circle_sdk import configuration


class TestMockAchAccountCreationRequest(unittest.TestCase):
    """MockAchAccountCreationRequest unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
