# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle_sdk
from circle_sdk.model.get_business_wire_account_response import GetBusinessWireAccountResponse
from circle_sdk import configuration


class TestGetBusinessWireAccountResponse(unittest.TestCase):
    """GetBusinessWireAccountResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
