# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle_sdk
from circle_sdk.model.list_transfers_response import ListTransfersResponse
from circle_sdk import configuration


class TestListTransfersResponse(unittest.TestCase):
    """ListTransfersResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
