# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle_sdk
from circle_sdk.model.wire_creation_request_us import WireCreationRequestUs
from circle_sdk import configuration


class TestWireCreationRequestUs(unittest.TestCase):
    """WireCreationRequestUs unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
