# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle_sdk
from circle_sdk.model.refund_payment_response import RefundPaymentResponse
from circle_sdk import configuration


class TestRefundPaymentResponse(unittest.TestCase):
    """RefundPaymentResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
