# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle_sdk
from circle_sdk.model.source_response import SourceResponse
from circle_sdk import configuration


class TestSourceResponse(unittest.TestCase):
    """SourceResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
