# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle_sdk
from circle_sdk.model.crypto_payments_money import CryptoPaymentsMoney
from circle_sdk import configuration


class TestCryptoPaymentsMoney(unittest.TestCase):
    """CryptoPaymentsMoney unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
