# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle_sdk
from circle_sdk.model.create_business_recipient_address_response import CreateBusinessRecipientAddressResponse
from circle_sdk import configuration


class TestCreateBusinessRecipientAddressResponse(unittest.TestCase):
    """CreateBusinessRecipientAddressResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
