# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle_sdk
from circle_sdk.model.wallet_location import WalletLocation
from circle_sdk import configuration


class TestWalletLocation(unittest.TestCase):
    """WalletLocation unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
