# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle_sdk
from circle_sdk.model.list_address_book_recipients_response import ListAddressBookRecipientsResponse
from circle_sdk import configuration


class TestListAddressBookRecipientsResponse(unittest.TestCase):
    """ListAddressBookRecipientsResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
