# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle_sdk
from circle_sdk.model.address_book_recipient_metadata import AddressBookRecipientMetadata
from circle_sdk import configuration


class TestAddressBookRecipientMetadata(unittest.TestCase):
    """AddressBookRecipientMetadata unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
