# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle_sdk
from circle_sdk.model.not_authorized import NotAuthorized
from circle_sdk import configuration


class TestNotAuthorized(unittest.TestCase):
    """NotAuthorized unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
