# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle_sdk
from circle_sdk.model.conflict import Conflict
from circle_sdk import configuration


class TestConflict(unittest.TestCase):
    """Conflict unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
