# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle_sdk
from circle_sdk.model.list_business_wire_accounts_response import ListBusinessWireAccountsResponse
from circle_sdk import configuration


class TestListBusinessWireAccountsResponse(unittest.TestCase):
    """ListBusinessWireAccountsResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
