# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle_sdk
from circle_sdk.model.wire_instruction_beneficiary_bank import WireInstructionBeneficiaryBank
from circle_sdk import configuration


class TestWireInstructionBeneficiaryBank(unittest.TestCase):
    """WireInstructionBeneficiaryBank unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
