
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-28T08:40:10+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "74240cd0b0266fae2949912d83d5bedd507c38af",
 "version": "0.13.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
