
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-23T23:11:05-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "af7829cb0cb49983c5e094a16d2306b9253d654c",
 "version": "0.0.142"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
