# coding: utf-8

"""
    Internal API

    SmartDiagnostics REST API for internal users only  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EdgeImagePrefixResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'prefix': 'str',
        'owner': 'EdgeImagePrefixOwnerChild',
        'note': 'str'
    }

    attribute_map = {
        'id': 'Id',
        'prefix': 'Prefix',
        'owner': 'Owner',
        'note': 'Note'
    }

    def __init__(self, id=None, prefix=None, owner=None, note=None):  # noqa: E501
        """EdgeImagePrefixResponse - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._prefix = None
        self._owner = None
        self._note = None
        self.discriminator = None
        self.id = id
        self.prefix = prefix
        self.owner = owner
        if note is not None:
            self.note = note

    @property
    def id(self):
        """Gets the id of this EdgeImagePrefixResponse.  # noqa: E501

        The id of the image prefix record  # noqa: E501

        :return: The id of this EdgeImagePrefixResponse.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this EdgeImagePrefixResponse.

        The id of the image prefix record  # noqa: E501

        :param id: The id of this EdgeImagePrefixResponse.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def prefix(self):
        """Gets the prefix of this EdgeImagePrefixResponse.  # noqa: E501

        Prefix string  # noqa: E501

        :return: The prefix of this EdgeImagePrefixResponse.  # noqa: E501
        :rtype: str
        """
        return self._prefix

    @prefix.setter
    def prefix(self, prefix):
        """Sets the prefix of this EdgeImagePrefixResponse.

        Prefix string  # noqa: E501

        :param prefix: The prefix of this EdgeImagePrefixResponse.  # noqa: E501
        :type: str
        """
        if prefix is None:
            raise ValueError("Invalid value for `prefix`, must not be `None`")  # noqa: E501

        self._prefix = prefix

    @property
    def owner(self):
        """Gets the owner of this EdgeImagePrefixResponse.  # noqa: E501


        :return: The owner of this EdgeImagePrefixResponse.  # noqa: E501
        :rtype: EdgeImagePrefixOwnerChild
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this EdgeImagePrefixResponse.


        :param owner: The owner of this EdgeImagePrefixResponse.  # noqa: E501
        :type: EdgeImagePrefixOwnerChild
        """
        if owner is None:
            raise ValueError("Invalid value for `owner`, must not be `None`")  # noqa: E501

        self._owner = owner

    @property
    def note(self):
        """Gets the note of this EdgeImagePrefixResponse.  # noqa: E501

        Prefix note  # noqa: E501

        :return: The note of this EdgeImagePrefixResponse.  # noqa: E501
        :rtype: str
        """
        return self._note

    @note.setter
    def note(self, note):
        """Sets the note of this EdgeImagePrefixResponse.

        Prefix note  # noqa: E501

        :param note: The note of this EdgeImagePrefixResponse.  # noqa: E501
        :type: str
        """

        self._note = note

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EdgeImagePrefixResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EdgeImagePrefixResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
