# coding: utf-8

"""
    Internal API

    SmartDiagnostics REST API for internal users only  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LocationPermissionCreateRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'location_id': 'str',
        'location_user_role': 'LocationUserRole'
    }

    attribute_map = {
        'location_id': 'LocationId',
        'location_user_role': 'LocationUserRole'
    }

    def __init__(self, location_id=None, location_user_role=None):  # noqa: E501
        """LocationPermissionCreateRequest - a model defined in Swagger"""  # noqa: E501
        self._location_id = None
        self._location_user_role = None
        self.discriminator = None
        self.location_id = location_id
        self.location_user_role = location_user_role

    @property
    def location_id(self):
        """Gets the location_id of this LocationPermissionCreateRequest.  # noqa: E501

        The location's ID  # noqa: E501

        :return: The location_id of this LocationPermissionCreateRequest.  # noqa: E501
        :rtype: str
        """
        return self._location_id

    @location_id.setter
    def location_id(self, location_id):
        """Sets the location_id of this LocationPermissionCreateRequest.

        The location's ID  # noqa: E501

        :param location_id: The location_id of this LocationPermissionCreateRequest.  # noqa: E501
        :type: str
        """
        if location_id is None:
            raise ValueError("Invalid value for `location_id`, must not be `None`")  # noqa: E501

        self._location_id = location_id

    @property
    def location_user_role(self):
        """Gets the location_user_role of this LocationPermissionCreateRequest.  # noqa: E501


        :return: The location_user_role of this LocationPermissionCreateRequest.  # noqa: E501
        :rtype: LocationUserRole
        """
        return self._location_user_role

    @location_user_role.setter
    def location_user_role(self, location_user_role):
        """Sets the location_user_role of this LocationPermissionCreateRequest.


        :param location_user_role: The location_user_role of this LocationPermissionCreateRequest.  # noqa: E501
        :type: LocationUserRole
        """
        if location_user_role is None:
            raise ValueError("Invalid value for `location_user_role`, must not be `None`")  # noqa: E501

        self._location_user_role = location_user_role

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LocationPermissionCreateRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LocationPermissionCreateRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
