# coding: utf-8

"""
    Internal API

    SmartDiagnostics REST API for internal users only  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WidgetTemplateChild(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'widget_template_name': 'str',
        'widget_template_description': 'str',
        'widget_template_filters': 'list[WidgetTemplateFilterChild]'
    }

    attribute_map = {
        'widget_template_name': 'WidgetTemplateName',
        'widget_template_description': 'WidgetTemplateDescription',
        'widget_template_filters': 'WidgetTemplateFilters'
    }

    def __init__(self, widget_template_name=None, widget_template_description=None, widget_template_filters=None):  # noqa: E501
        """WidgetTemplateChild - a model defined in Swagger"""  # noqa: E501
        self._widget_template_name = None
        self._widget_template_description = None
        self._widget_template_filters = None
        self.discriminator = None
        self.widget_template_name = widget_template_name
        if widget_template_description is not None:
            self.widget_template_description = widget_template_description
        self.widget_template_filters = widget_template_filters

    @property
    def widget_template_name(self):
        """Gets the widget_template_name of this WidgetTemplateChild.  # noqa: E501


        :return: The widget_template_name of this WidgetTemplateChild.  # noqa: E501
        :rtype: str
        """
        return self._widget_template_name

    @widget_template_name.setter
    def widget_template_name(self, widget_template_name):
        """Sets the widget_template_name of this WidgetTemplateChild.


        :param widget_template_name: The widget_template_name of this WidgetTemplateChild.  # noqa: E501
        :type: str
        """
        if widget_template_name is None:
            raise ValueError("Invalid value for `widget_template_name`, must not be `None`")  # noqa: E501

        self._widget_template_name = widget_template_name

    @property
    def widget_template_description(self):
        """Gets the widget_template_description of this WidgetTemplateChild.  # noqa: E501


        :return: The widget_template_description of this WidgetTemplateChild.  # noqa: E501
        :rtype: str
        """
        return self._widget_template_description

    @widget_template_description.setter
    def widget_template_description(self, widget_template_description):
        """Sets the widget_template_description of this WidgetTemplateChild.


        :param widget_template_description: The widget_template_description of this WidgetTemplateChild.  # noqa: E501
        :type: str
        """

        self._widget_template_description = widget_template_description

    @property
    def widget_template_filters(self):
        """Gets the widget_template_filters of this WidgetTemplateChild.  # noqa: E501


        :return: The widget_template_filters of this WidgetTemplateChild.  # noqa: E501
        :rtype: list[WidgetTemplateFilterChild]
        """
        return self._widget_template_filters

    @widget_template_filters.setter
    def widget_template_filters(self, widget_template_filters):
        """Sets the widget_template_filters of this WidgetTemplateChild.


        :param widget_template_filters: The widget_template_filters of this WidgetTemplateChild.  # noqa: E501
        :type: list[WidgetTemplateFilterChild]
        """
        if widget_template_filters is None:
            raise ValueError("Invalid value for `widget_template_filters`, must not be `None`")  # noqa: E501

        self._widget_template_filters = widget_template_filters

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WidgetTemplateChild, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WidgetTemplateChild):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
