DEFAULT_LOG_LEVEL = "info"

DEFAULT_DEVICE = "/dev/ttyUSB1"
BAUD_RATE = 57600

SLEEP_TIME = 0.001

SERIAL_TIMEOUT = 0.001
NETWORK_TIMEOUT = 10

CMD_ID_SIZE = 4
CMD_ID_PACK = '!I'  # !Q for 8 bytes

UART_SEND_BYTES = 127
