VERSION_YEAR = 2022
VERSION_MONTH = int('11')
VERSION_DAY = int('28')
VERSION_HOUR = int('18')
VERSION_MINUTE = int('31')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202211281831
version_date = '2022/11/28 18:31'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
