
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-25T04:48:10+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8b74840f3dd47a262f90d4f99be6068713d7f688",
 "version": "1.17.1.post0.dev528"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
