
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-24T08:59:21+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "51a58e6b6ac607ba2430c424c06eb64e80966ea4",
 "version": "v0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
