
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-29T11:46:20+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8d8185e2e7534edd5aa6511d4f28e8bceb10afbf",
 "version": "1.17.1.post0.dev559"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
