# coding: utf-8

"""
    Internal API

    SmartDiagnostics REST API for internal users only  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ActivityEventDocumentRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'document_url': 'str',
        'document_name': 'str'
    }

    attribute_map = {
        'document_url': 'DocumentUrl',
        'document_name': 'DocumentName'
    }

    def __init__(self, document_url=None, document_name=None):  # noqa: E501
        """ActivityEventDocumentRequest - a model defined in Swagger"""  # noqa: E501
        self._document_url = None
        self._document_name = None
        self.discriminator = None
        self.document_url = document_url
        self.document_name = document_name

    @property
    def document_url(self):
        """Gets the document_url of this ActivityEventDocumentRequest.  # noqa: E501

        Document URL  # noqa: E501

        :return: The document_url of this ActivityEventDocumentRequest.  # noqa: E501
        :rtype: str
        """
        return self._document_url

    @document_url.setter
    def document_url(self, document_url):
        """Sets the document_url of this ActivityEventDocumentRequest.

        Document URL  # noqa: E501

        :param document_url: The document_url of this ActivityEventDocumentRequest.  # noqa: E501
        :type: str
        """
        if document_url is None:
            raise ValueError("Invalid value for `document_url`, must not be `None`")  # noqa: E501

        self._document_url = document_url

    @property
    def document_name(self):
        """Gets the document_name of this ActivityEventDocumentRequest.  # noqa: E501

        Document Name  # noqa: E501

        :return: The document_name of this ActivityEventDocumentRequest.  # noqa: E501
        :rtype: str
        """
        return self._document_name

    @document_name.setter
    def document_name(self, document_name):
        """Sets the document_name of this ActivityEventDocumentRequest.

        Document Name  # noqa: E501

        :param document_name: The document_name of this ActivityEventDocumentRequest.  # noqa: E501
        :type: str
        """
        if document_name is None:
            raise ValueError("Invalid value for `document_name`, must not be `None`")  # noqa: E501

        self._document_name = document_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ActivityEventDocumentRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ActivityEventDocumentRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
