# coding: utf-8

"""
    Internal API

    SmartDiagnostics REST API for internal users only  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class IndicatorTypeCategoryChild(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'indicator_type_category': 'MetricTypeCodeCategory',
        'name': 'str'
    }

    attribute_map = {
        'id': 'Id',
        'indicator_type_category': 'IndicatorTypeCategory',
        'name': 'Name'
    }

    def __init__(self, id=None, indicator_type_category=None, name=None):  # noqa: E501
        """IndicatorTypeCategoryChild - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._indicator_type_category = None
        self._name = None
        self.discriminator = None
        self.id = id
        self.indicator_type_category = indicator_type_category
        self.name = name

    @property
    def id(self):
        """Gets the id of this IndicatorTypeCategoryChild.  # noqa: E501

        The numeric representation of the indicator type category  # noqa: E501

        :return: The id of this IndicatorTypeCategoryChild.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this IndicatorTypeCategoryChild.

        The numeric representation of the indicator type category  # noqa: E501

        :param id: The id of this IndicatorTypeCategoryChild.  # noqa: E501
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def indicator_type_category(self):
        """Gets the indicator_type_category of this IndicatorTypeCategoryChild.  # noqa: E501


        :return: The indicator_type_category of this IndicatorTypeCategoryChild.  # noqa: E501
        :rtype: MetricTypeCodeCategory
        """
        return self._indicator_type_category

    @indicator_type_category.setter
    def indicator_type_category(self, indicator_type_category):
        """Sets the indicator_type_category of this IndicatorTypeCategoryChild.


        :param indicator_type_category: The indicator_type_category of this IndicatorTypeCategoryChild.  # noqa: E501
        :type: MetricTypeCodeCategory
        """
        if indicator_type_category is None:
            raise ValueError("Invalid value for `indicator_type_category`, must not be `None`")  # noqa: E501

        self._indicator_type_category = indicator_type_category

    @property
    def name(self):
        """Gets the name of this IndicatorTypeCategoryChild.  # noqa: E501

        The UI friendly string representation of the indicator type category  # noqa: E501

        :return: The name of this IndicatorTypeCategoryChild.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this IndicatorTypeCategoryChild.

        The UI friendly string representation of the indicator type category  # noqa: E501

        :param name: The name of this IndicatorTypeCategoryChild.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IndicatorTypeCategoryChild, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IndicatorTypeCategoryChild):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
