# coding: utf-8

"""
    Internal API

    SmartDiagnostics REST API for internal users only  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InstallAddUserResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'install_id': 'str',
        'success_count': 'int',
        'error_count': 'int'
    }

    attribute_map = {
        'install_id': 'InstallId',
        'success_count': 'SuccessCount',
        'error_count': 'ErrorCount'
    }

    def __init__(self, install_id=None, success_count=None, error_count=None):  # noqa: E501
        """InstallAddUserResponse - a model defined in Swagger"""  # noqa: E501
        self._install_id = None
        self._success_count = None
        self._error_count = None
        self.discriminator = None
        self.install_id = install_id
        self.success_count = success_count
        self.error_count = error_count

    @property
    def install_id(self):
        """Gets the install_id of this InstallAddUserResponse.  # noqa: E501


        :return: The install_id of this InstallAddUserResponse.  # noqa: E501
        :rtype: str
        """
        return self._install_id

    @install_id.setter
    def install_id(self, install_id):
        """Sets the install_id of this InstallAddUserResponse.


        :param install_id: The install_id of this InstallAddUserResponse.  # noqa: E501
        :type: str
        """
        if install_id is None:
            raise ValueError("Invalid value for `install_id`, must not be `None`")  # noqa: E501

        self._install_id = install_id

    @property
    def success_count(self):
        """Gets the success_count of this InstallAddUserResponse.  # noqa: E501


        :return: The success_count of this InstallAddUserResponse.  # noqa: E501
        :rtype: int
        """
        return self._success_count

    @success_count.setter
    def success_count(self, success_count):
        """Sets the success_count of this InstallAddUserResponse.


        :param success_count: The success_count of this InstallAddUserResponse.  # noqa: E501
        :type: int
        """
        if success_count is None:
            raise ValueError("Invalid value for `success_count`, must not be `None`")  # noqa: E501

        self._success_count = success_count

    @property
    def error_count(self):
        """Gets the error_count of this InstallAddUserResponse.  # noqa: E501


        :return: The error_count of this InstallAddUserResponse.  # noqa: E501
        :rtype: int
        """
        return self._error_count

    @error_count.setter
    def error_count(self, error_count):
        """Sets the error_count of this InstallAddUserResponse.


        :param error_count: The error_count of this InstallAddUserResponse.  # noqa: E501
        :type: int
        """
        if error_count is None:
            raise ValueError("Invalid value for `error_count`, must not be `None`")  # noqa: E501

        self._error_count = error_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InstallAddUserResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InstallAddUserResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
