
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-25T07:17:12+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b01ac96889158e688368d9dbe0c0874a75cacb2e",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
