column_name_map = {
    'inlay_type': ['inlay', 'inlay_type', 'antennaType', 'antenna_type', 'inlayType'],
    'common_run_name': ['common_run_name', 'commonRunName'],
    'tag_run_location': ['tag_run_location', 'tag_location', 'tagLocation'],
    'status_offline': ['status_offline', 'chosenTagStatus'],
    'fail_bin': ['fail_bin', 'chosenTagStatus'],
    'external_id': ['external_id', 'externalId'],
    'selected_tag': ['selected_tag', 'chosenTagInLocation'],
    'packet_version': ['packet_ver'],
    'flow_version': ['flow_ver'],
    'test_name': ['name'],
    'test_status_offline': ['status_offline'],
    'received_packet_count': ['num_packets'],
    'test_time_profile_period': ['timeProfile_u'],
    'test_time_profile_on_time': ['timeProfile_l'],
    'test_energizing_pattern': ['energizingPattern'],
    'test_receive_ch': ['rxChannel'],
    'test_pl_delay': ['plDelay'],
    'test_min_packets': ['minPackets'],
    'test_max_time': ['maxTime'],
    'test_post_delay': ['delayBeforeNextTest'],
    'test_ttfp_lsl': ['ttfp_l'], 'test_ttfp_usl': ['ttfp_u'],
    'test_tbp_min_lsl': ['tbp_min_l'], 'test_tbp_min_usl': ['tbp_min_u'],
    'test_tbp_max_lsl': ['tbp_max_l'], 'test_tbp_max_usl': ['tbp_max_u'],
    'test_tbp_avg_lsl': ['tbp_mean_l'], 'test_tbp_avg_usl': ['tbp_mean_u'],
    'test_sprinkler_counter_max_lsl': ['sprinkler_counter_max_l'],
    'test_sprinkler_counter_max_usl': ['sprinkler_counter_max_u'],
    'test_res_rssi_avg': ['rssi_mean'],
    'test_res_tbp_avg': ['tbp_mean'],
    'rssi_avg': ['rssi_mean'],
    'tbp_avg': ['tbp_mean'],
    'first_packet_counter': ['packet_counter_first'],
    'last_packet_counter': ['packet_counter_last'],
    'min_tx_frequency_last': ['min_tx_last'],
    'packets_per_cycle_avg': ['sprinkler_counter_mean'],
    'packets_per_cycle_std': ['sprinkler_counter_std'],
    'internal_temperature_avg': ['temperature_mean'],
    'aux_meas_avg': ['axu_meas_mean'],
    'total_location_duration': ['total_location_duration', 'total_run_duration'],
    'test_rssi_hw_threshold': ['rssiThresholdHW'], 'test_rssi_acceptable_threshold': ['rssiThresholdSW'],
    'time_between_cycles_avg': ['tbc_mean'],
    'state': ['state(tbp_exists:0,no_tbp:-1,no_ttfp:-2,dup_adv_address:-3)']
}
