# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: th2_grpc_sense/sense.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ath2_grpc_sense/sense.proto\x12\tth2.sense\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x89\x01\n\x13NotificationRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x31\n\x0b\x64\x65scription\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x31\n\x0f\x65xpected_events\x18\x03 \x03(\x0b\x32\x18.th2.sense.ExpectedEvent\"B\n\rExpectedEvent\x12\"\n\x04type\x18\x01 \x01(\x0b\x32\x14.th2.sense.EventType\x12\r\n\x05\x63ount\x18\x02 \x01(\x04\"\x19\n\tEventType\x12\x0c\n\x04name\x18\x01 \x01(\t2Q\n\x05Sense\x12H\n\x0eNotifyOnEvents\x12\x1e.th2.sense.NotificationRequest\x1a\x16.google.protobuf.EmptyB\x1f\n\x1b\x63om.exactpro.th2.sense.grpcP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'th2_grpc_sense.sense_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033com.exactpro.th2.sense.grpcP\001'
  _NOTIFICATIONREQUEST._serialized_start=103
  _NOTIFICATIONREQUEST._serialized_end=240
  _EXPECTEDEVENT._serialized_start=242
  _EXPECTEDEVENT._serialized_end=308
  _EVENTTYPE._serialized_start=310
  _EVENTTYPE._serialized_end=335
  _SENSE._serialized_start=337
  _SENSE._serialized_end=418
# @@protoc_insertion_point(module_scope)
