from ispyb_client.paths.ispyb_api_v1_legacy_token_proposal_proposal_id_em_datacollection_datacollection_id_movie_movie_id_motioncorrection_thumbnail.get import ApiForget


class IspybApiV1LegacyTokenProposalProposalIdEmDatacollectionDatacollectionIdMovieMovieIdMotioncorrectionThumbnail(
    ApiForget,
):
    pass
