
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-25T14:06:31+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "7f801adce1b204469bdf95fae82b110d6cf59299",
 "version": "0.17.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
