# coding: utf-8

"""
    py-ISPyB

    FastAPI Prototype  # noqa: E501

    The version of the OpenAPI document: 0.1alpha
    Generated by: https://openapi-generator.tech
"""

import unittest

import ispyb_client
from ispyb_client.model.data_collection_meta_data import DataCollectionMetaData
from ispyb_client import configuration


class TestDataCollectionMetaData(unittest.TestCase):
    """DataCollectionMetaData unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
