#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2204-100-gd976e27b"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2204
#define NETGEN_VERSION_TWEAK 100
#define NETGEN_VERSION_HASH "gd976e27b"
#endif // NETGEN_VERSION_HPP_INCLUDED
